### ISSUE TITLE
Error with official script

### ISSUE THREAD

**Issue by danfriedman0** [diegma/neural-dep-srl#1]
I'm trying to replicate the results from you SRL paper (https://arxiv.org/pdf/1701.02593.pdf). I've been able to get the code to run and train, but at every iteration I get a message saying that there's an error with the official script. When I run the conll evaluation script myself on the output from the model (`prediction_09.paste`) the first error is a line mismatch at line 634, which is the line immediately after a sentence ("Two - Way Street") with no predicate in it: in the gold file this line is blank, but the system output file has five tab-separated underscores. When I delete the line, other lines later in the file raise another error, "Invalid number of tokens in line."

Do you know how to fix this problem? Or can you explain the parts of the code that write the output, so I can try to figure it out myself? Thanks!

**Comment by diegma** [comment]
Hi Dan,
just remove from your gold standard all the sentences without predicates and make sure that predictions and gold standard have the same lines (watch out for double newlines, etc.).
It should work.

**Comment by danfriedman0** [comment]
That worked, thanks!
