### ISSUE TITLE
CoNLL 2009 Data Unavailable?

### ISSUE THREAD

**Issue by egaebel** [diegma/neural-dep-srl#2]
I'm trying to run your code, but the links to download the ConLL 2009 data are mostly dead links. Do you have a direct link to the data you used in training/eval?

**Comment by diegma** [comment]
Unfortunately I cannot share the connl 2009 data since they are under LDC licence, https://catalog.ldc.upenn.edu/LDC2012T04.

**Comment by svjan5** [comment]
Hi,
I also don't have access to ConLL 2009 dataset. Without that it is becoming hard to understand the entire code. Please provide some more comments for the function [get_adj(deps, degree)](https://github.com/diegma/neural-dep-srl/blob/master/nnet/run/srl/read_dependency.py#L24). I am unable to infer the the form of `deps` and `degree` arguments to this function. If possible please explain it using an example sentence from the dataset.

Thank you in advance

**Comment by egaebel** [comment]
I understand that you cannot upload the data yourself, but do you have a link to somewhere to download the data? You must have downloaded it from somewhere, can you share that link? The one your provide in your instructions doesn't have a working download link.

**Comment by svjan5** [comment]
@egaebel you need to pay for the data to get it. It is not freely available.

**Comment by egaebel** [comment]
@svjan5 Yeah I realized that after digging for a while. However even the links provided don't lead to somewhere you can pay for them. They're just dead.

**Comment by ShiYaya** [comment]
If the ConLL 2009 dataset is not public, you can provide a small set of data made by your own to make the program run, so that we can understand the code more easily

**Comment by MrSingh-bytes** [comment]
Hi,
Which version of Theano and Lasagne is fine for this?
I think lasagne=0.1 works with python 2.7 and 3.4.
But I am still getting error while running the training.sh script.
Please let me know . Thank you
